version: 0.2

phases:
  pre_build:
    commands:
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew clean check assembleDebug
  post_build:
    commands:
      - echo Build completed on `date`
  install:
    runtime-versions:
      android: 29

cache:
  paths:
    - '/root/.gradle/caches/'
    - '/root/.gradle/caches/**/*'